import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import Script from "next/script"
import "./globals.css"
import { Providers } from '@/components/providers'
import { CommandMenu } from "@/components/command-menu"
import { ChatButton } from "@/components/chat-button"
import { cn } from "@/lib/utils"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Presense",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn(
      geistSans.variable, 
      geistMono.variable
    )}>
      <head>
        <Script 
          src="https://kit.fontawesome.com/bdf22b7d6d.js" 
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
      </head>
      <body>
        <Providers>
          {children}
          <ChatButton />
          <CommandMenu />
        </Providers>
      </body>
    </html>
  )
}
