import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { ModalProvider } from '@/components/modals/modal-context'
import { Toaster } from 'sonner'
import { ChatProvider } from "@/components/chat/chat-context"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <ChatProvider>
                    <ModalProvider>
                        {children}
                    </ModalProvider>
                </ChatProvider>
                <Toaster />
            </body>
        </html>
    )
}
