name: Sync Platforms

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            ${{ secrets.APP_URL }}/api/cron/sync-platforms 